---
- name: Creating the users.
  user:
    name: "{{ sname }}"
    password:  "{{ 'admin' | password_hash('sha512')  }}"
    comment: "{{ sfull }}"
    shell: /bin/bash
    group: wheel
    groups: wheels
    home: /home/{{ sname }}
